const base='https://governed-agent-email.markbarsenas366.chatgpt.site/api/v1';
export default function Docs(){return <main className="landing"><nav className="topnav"><a className="brand" href="/">AgentMail</a><a className="button" href="/dashboard">Dashboard →</a></nav><section className="platform" style={{display:'block',maxWidth:950}}><div className="eyebrow">DEVELOPER GUIDE</div><h1>Send your first email</h1><p>Create a workspace, add a domain, publish its DNS records, and verify it. Then create an API key. Keep keys on your server.</p><h2 style={{fontSize:28}}>Send API</h2><pre className="code">{String.raw`curl '${base}/emails' \
  -H "Authorization: Bearer $AGENTMAIL_API_KEY" \
  -H 'Content-Type: application/json' \
  -H 'Idempotency-Key: welcome-user-123' \
  -d '{"from":"team@yourdomain.com","to":"customer@example.com","subject":"Welcome","text":"Your account is ready."}'`}</pre><p>A new accepted request returns <code>202</code> with an email ID. Repeating the same request and idempotency key returns the existing result without another send. A key reused with different content returns <code>409</code>. Preserve the same key on retries, including timeouts. Retry uncertain requests after three minutes; the safe retry window is 23 hours.</p><p><code>from</code>, <code>to</code>, <code>subject</code>, and <code>text</code> are required. <code>to</code> accepts one address or an array of up to 50. <code>reply_to</code> is optional. Only verified domains owned by your workspace can send.</p><h2 style={{fontSize:28}}>Receive email</h2><p>Enable receiving on a dedicated domain or subdomain and publish its MX records. This changes where that domain receives email, so preserve your existing inbox by using a separate subdomain.</p><pre className="code">{String.raw`curl '${base}/received' \
  -H "Authorization: Bearer $AGENTMAIL_API_KEY"`}</pre><p>Returns the most recent 100 inbound messages for your workspace, including <code>id</code>, <code>from_address</code>, <code>to_addresses</code>, <code>subject</code>, <code>text_body</code>, and <code>created_at</code>. Emails received before this API was enabled are available in the agent conversation history when applicable.</p><h2 style={{fontSize:28}}>Verify webhooks</h2><p>Add an HTTPS destination in Webhooks and save its one-time signing secret. Events include a stable ID, type, timestamp, and data. Verify HMAC-SHA256 using the exact raw request body:</p><pre className="code">{`signed_content = webhook-id + "." + webhook-timestamp + "." + raw_body
expected = HMAC_SHA256(signing_secret, signed_content).hex()
received = webhook-signature without the "v1=" prefix`}</pre><p>Compare signatures in constant time, reject timestamps more than five minutes old, and deduplicate events by <code>webhook-id</code>. Return a successful HTTP status promptly. Expect duplicate deliveries.</p><p>Failed deliveries are persisted and retried with backoff during API, provider webhook, or dashboard activity, up to six attempts. You can also retry manually. Background retries are scheduled every five minutes. Scheduling delays can occur; this preview has no delivery-time guarantee.</p><h2 style={{fontSize:28}}>Limits and status</h2><p>The free developer allowance is 100 API recipients per calendar month in UTC. Each recipient counts once. Pending or uncertain sends reserve their allowance until acceptance is resolved. A limit response is <code>429</code>; an invalid key is <code>401</code>; an unowned or unverified domain is <code>403</code>. Accepted means the delivery provider accepted the message. Delivered, bounced, and failed events update the log when the provider reports them.</p><p>Paid checkout remains unavailable until AgentMail’s dedicated billing account is configured. Governed agents keep their existing approval rules and are separate from the transactional send API.</p></section></main>}
