'use client';
import {useEffect,useState} from 'react';
type Row=Record<string,any>;
export default function Inbox({pilot=false}:{pilot?:boolean}){const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[signedOut,setSignedOut]=useState(false),[requestId,setRequestId]=useState('');
 async function load(){const r=await fetch('/api/support',{cache:'no-store'});if(r.status===401){setSignedOut(true);return;}const b=await r.json();if(!r.ok)throw Error(b.error);setData(b);}
 useEffect(()=>{setRequestId(crypto.randomUUID());load().catch(e=>setError(e.message));},[]);
 async function send(body:Row){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error);setNotice(body.action==='reply'?'Reply saved. The customer can read it here.':'Request saved. Return here to check for a reply.');await load();if(!body.action)setRequestId(crypto.randomUUID());}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{setBusy(false);}}
 if(signedOut)return <section className="panel"><h2>Contact the team</h2><p>Sign in with email or Google, then return here to send a request. You do not need a paid plan or a workspace.</p><a className="button" href={pilot?"/sign-in?return_to=/try-ai":"/sign-in?return_to=/support"}>Sign in to contact support</a></section>;
 return <>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<form className="panel form-grid" onSubmit={e=>{e.preventDefault();send({...Object.fromEntries(new FormData(e.currentTarget)),request_id:requestId});}}><h2 className="wide">Send a request</h2><label>Topic<select name="category" defaultValue={pilot?"ai_allowance":"technical"}><option value="technical">Technical help</option><option value="billing">Billing</option><option value="ai_allowance">AI drafting allowance</option><option value="privacy">Privacy or deletion request</option><option value="abuse">Report abuse</option></select></label><label>Subject<input name="subject" defaultValue={pilot?"Request AI drafting pilot access":""} required minLength={3} maxLength={150}/></label><label className="wide">What can we help with?<textarea name="message" defaultValue={pilot?"Workspace name: \nIntended use: \nEstimated monthly draft attempts: \nI plan to start with human approval required.":""} required minLength={10} maxLength={6000}/></label><p className="caption wide">Include the workspace name and relevant message or event ID. Do not include API keys, passwords, payment card details, or private email contents. Replies appear below; email notifications are not enabled.</p><button disabled={busy||!requestId||!data} aria-busy={busy}>Submit request</button></form><section className="panel"><div className="panel-header"><h2>{data?.admin?'Operator support inbox':'Your requests'}</h2><button className="secondary" onClick={()=>load().catch(e=>setError(e.message))}>Refresh replies</button></div>{!data?<p>Loading requests…</p>:!data.requests.length?<p>No requests yet.</p>:data.requests.map((r:Row)=><article className="record" key={r.id}><div className="record-head"><h3>{r.subject}</h3><span className="badge">{r.status}</span></div><p className="caption">{r.category} · {new Date(r.created_at).toLocaleString()}{data.admin?' · '+r.requester_email:''}</p><p style={{whiteSpace:'pre-wrap'}}>{r.message}</p>{r.reply&&<div className="message-body"><strong>Support reply</strong><p>{r.reply}</p></div>}{data.admin&&<form className="stack" onSubmit={e=>{e.preventDefault();send({...Object.fromEntries(new FormData(e.currentTarget)),id:r.id,action:'reply'});}}><label>Reply<textarea name="reply" defaultValue={r.reply} required maxLength={6000}/></label><label>Status<select name="status" defaultValue={r.status}><option value="open">Open</option><option value="resolved">Resolved</option></select></label><button disabled={busy}>Save reply</button></form>}</article>)}</section></>;}
