import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Queue} from './queue.mjs';
import {returnPath,processBounce} from './bounces.mjs';
process.env.BOUNCE_DOMAIN='bounces.senderpermit.com';process.env.BOUNCE_SECRET='test-only-secret-'.repeat(4);
const workspace='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',other='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const body={workspace,message:{from:'hello@example.com',to:['user@example.net'],subject:'test',text:'test'}};
function setup(){const q=new Queue(':memory:');const s=q.submit(body,'first',['example.com']);const row=q.claim();q.finish(row.id,'mta_accepted');return {q,s,row};}
test('signed correlation rejects forgery, wrong recipient and unknown message',()=>{const {q,row}=setup();try{const report=[{recipient:'user@example.net',action:'failed',status:'5.1.1'}];const address=returnPath(row.id);assert.equal(processBounce(q,address.replace('@','x@'),report),false);assert.equal(processBounce(q,address,[{...report[0],recipient:'other@example.net'}]),false);assert.equal(processBounce(q,returnPath('cccccccc-cccc-4ccc-8ccc-cccccccccccc'),report),false);assert.equal(q.db.prepare('SELECT count(*) n FROM suppressions').get().n,0);}finally{q.close();}});
test('hard bounce persists once, suppresses only same workspace and queued mail',()=>{const {q,s,row}=setup();try{q.submit(body,'queued',['example.com']);const report=[{recipient:'user@example.net',action:'failed',status:'5.1.1'}];assert.equal(processBounce(q,returnPath(row.id),report),true);assert.equal(processBounce(q,returnPath(row.id),report),false);assert.equal(q.status(workspace,s.id)[0].state,'bounced');assert.equal(q.claim(),null);const next=q.submit(body,'future',['example.com']);assert.equal(q.status(workspace,next.id)[0].state,'suppressed');const isolated=q.submit({...body,workspace:other},'future',['example.com']);assert.equal(q.status(other,isolated.id)[0].state,'queued');}finally{q.close();}});
test('delays never requeue mail; policy failures do not suppress; late delay cannot undo bounce',()=>{const {q,s,row}=setup();try{const send=(action,status)=>processBounce(q,returnPath(row.id),[{recipient:'user@example.net',action,status}]);send('delayed','4.2.2');assert.equal(q.status(workspace,s.id)[0].state,'deferred');assert.equal(q.claim(),undefined);send('failed','5.7.1');assert.equal(q.status(workspace,s.id)[0].state,'bounced');send('delayed','4.4.1');assert.equal(q.status(workspace,s.id)[0].state,'bounced');assert.equal(q.db.prepare('SELECT count(*) n FROM suppressions').get().n,0);}finally{q.close();}});
