import {DatabaseSync} from 'node:sqlite';
import {randomUUID,createHash} from 'node:crypto';
import {z} from 'zod';
const address=z.string().email().max(254).regex(/^[\x21-\x7e]+$/).refine(s=>!/[\r\n<>]/.test(s)&&!s.startsWith('-'));
export const envelope=z.object({workspace:z.string().uuid(),message:z.object({from:address,to:z.array(address).min(1).max(50),subject:z.string().min(1).max(998).regex(/^[^\r\n]*$/),text:z.string().max(200000),replyTo:address.optional(),headers:z.record(z.string().max(998).regex(/^[^\r\n]*$/)).optional().refine(h=>!h||Object.keys(h).every(k=>['In-Reply-To','References','Auto-Submitted'].includes(k)))}).strict()}).strict();
export class Queue {
 constructor(path){this.db=new DatabaseSync(path);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
 CREATE TABLE IF NOT EXISTS submissions(id TEXT PRIMARY KEY,workspace TEXT NOT NULL,key TEXT NOT NULL,hash TEXT NOT NULL,payload TEXT NOT NULL,created INTEGER NOT NULL,UNIQUE(workspace,key));
 CREATE TABLE IF NOT EXISTS recipients(id TEXT PRIMARY KEY,submission TEXT NOT NULL REFERENCES submissions(id),recipient TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'queued',lease INTEGER,error TEXT,UNIQUE(submission,recipient));
 CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,recipient_id TEXT NOT NULL,state TEXT NOT NULL,at INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS suppressions(workspace TEXT NOT NULL,recipient TEXT NOT NULL,reason TEXT NOT NULL,PRIMARY KEY(workspace,recipient));`);}
 submit(input,key,allowedDomains){const b=envelope.parse(input);if(!/^[a-zA-Z0-9_./:-]{1,128}$/.test(key))throw Object.assign(Error('Invalid idempotency key'),{status:400});if(!allowedDomains.includes(b.message.from.split('@')[1].toLowerCase()))throw Object.assign(Error('Sender domain not provisioned for this workspace'),{status:403});const payload=JSON.stringify(b.message),hash=createHash('sha256').update(payload).digest('hex');this.db.exec('BEGIN IMMEDIATE');try{const old=this.db.prepare('SELECT * FROM submissions WHERE workspace=? AND key=?').get(b.workspace,key);if(old){if(old.hash!==hash)throw Object.assign(Error('Key belongs to another message'),{status:409});this.db.exec('COMMIT');return {id:old.id,stage:'queued',replayed:true};}const count=this.db.prepare("SELECT count(*) n FROM recipients WHERE state IN ('queued','submitting')").get().n;if(count+b.message.to.length>10000)throw Object.assign(Error('Queue capacity reached'),{status:503});const id='sp_'+randomUUID();this.db.prepare('INSERT INTO submissions VALUES(?,?,?,?,?,?)').run(id,b.workspace,key,hash,payload,Date.now());for(const to of new Set(b.message.to)){const blocked=this.db.prepare('SELECT 1 FROM suppressions WHERE workspace=? AND recipient=?').get(b.workspace,to.toLowerCase());const rid=randomUUID(),state=blocked?'suppressed':'queued';this.db.prepare('INSERT INTO recipients(id,submission,recipient,state) VALUES(?,?,?,?)').run(rid,id,to,state);this.db.prepare('INSERT INTO events(recipient_id,state,at) VALUES(?,?,?)').run(rid,state,Date.now());}this.db.exec('COMMIT');return {id,stage:'queued',replayed:false};}catch(e){this.db.exec('ROLLBACK');throw e;}}
 claim(){this.db.exec('BEGIN IMMEDIATE');try{const row=this.db.prepare("SELECT r.*,s.payload,s.workspace FROM recipients r JOIN submissions s ON s.id=r.submission WHERE r.state='queued' ORDER BY s.created,r.id LIMIT 1").get();if(row){const blocked=this.db.prepare('SELECT 1 FROM suppressions WHERE workspace=? AND recipient=?').get(row.workspace,row.recipient.toLowerCase());const state=blocked?'suppressed':'submitting';this.db.prepare('UPDATE recipients SET state=?,lease=? WHERE id=?').run(state,Date.now()+120000,row.id);this.db.prepare('INSERT INTO events(recipient_id,state,at) VALUES(?,?,?)').run(row.id,state,Date.now());if(blocked){this.db.exec('COMMIT');return null;}}this.db.exec('COMMIT');return row;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 finish(id,state){if(!['mta_accepted','uncertain'].includes(state))throw Error('Invalid outcome');this.db.exec('BEGIN IMMEDIATE');try{const r=this.db.prepare("UPDATE recipients SET state=?,lease=NULL WHERE id=? AND state='submitting' RETURNING id").get(state,id);if(r)this.db.prepare('INSERT INTO events(recipient_id,state,at) VALUES(?,?,?)').run(id,state,Date.now());this.db.exec('COMMIT');}catch(e){this.db.exec('ROLLBACK');throw e;}}
 recover(){const rows=this.db.prepare("SELECT id FROM recipients WHERE state='submitting' AND lease<?").all(Date.now());for(const r of rows)this.finish(r.id,'uncertain');}
 status(workspace,id){return this.db.prepare('SELECT r.recipient,r.state FROM recipients r JOIN submissions s ON s.id=r.submission WHERE s.workspace=? AND s.id=?').all(workspace,id);}
 close(){this.db.close();}
}
