 'use client';
import {useEffect,useState} from 'react';
type Row=Record<string,any>;
export function WorkspacePicker({current}:{current?:Row}){
 const [rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[create,setCreate]=useState(false);
 useEffect(()=>{fetch('/api/workspaces').then(async r=>{const b=await r.json();if(!r.ok)throw Error(b.error);setRows(b.workspaces);}).catch(e=>setError(e.message));},[]);
 async function save(body:Row){setBusy(true);setError('');try{const r=await fetch('/api/workspaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error);window.location.reload();}catch(e){setError(e instanceof Error?e.message:'Unable to change workspace');setBusy(false);}}
 return <div style={{margin:'12px 0'}}><label>Active workspace<select aria-label="Switch workspace" value={current?.id||''} disabled={busy||!current} onChange={e=>save({action:'switch',id:e.target.value})}>{!current&&<option>Loading…</option>}{rows.map(w=><option key={w.id} value={w.id}>{w.name} · {w.id.slice(0,6)}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>setCreate(!create)} style={{marginTop:8}}>New workspace +</button>{create&&<form className="stack" onSubmit={e=>{e.preventDefault();save({action:'create',name:new FormData(e.currentTarget).get('name'),request_id:crypto.randomUUID()});}}><label>Workspace name<input name="name" minLength={2} maxLength={100} required placeholder="Your company or project"/></label><button disabled={busy}>Create workspace</button></form>}{error&&<p role="alert">{error}</p>}</div>;
}
export function SignOut(){const [busy,setBusy]=useState(false),[error,setError]=useState('');return <><button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch('/api/sign-out',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const b=await r.json();if(!r.ok)throw Error(b.error);window.location.assign(b.redirect);}catch{setError('Sign out failed. Try again.');setBusy(false);}}}>{busy?'Signing out…':'Sign out'}</button>{error&&<span role="alert">{error}</span>}</>;}
export function SetupGuide({data,domains,email,navigate}:{data:Row;domains:Row[];email:string;navigate:(tab:string)=>void}){
 const verified=domains.filter(d=>d.status==='verified'),key=data.apiKeys.some((k:Row)=>!k.revoked_at),sent=data.emailApiEvents.some((e:Row)=>e.provider_id);
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId]=useState(()=>crypto.randomUUID());
 return <section className="panel"><h2>{sent?'Your email setup':'Get started with AgentMail'}</h2><ol className="setup-steps"><li><strong>{verified.length?'✓ ':''}Verify your domain</strong><p>Add the DNS records at your domain host, then verify them.</p><button className="secondary" onClick={()=>navigate('Domains')}>Manage domains</button></li><li><strong>{key?'✓ ':''}Create an API key</strong><p>Copy and save the key for your application.</p><button className="secondary" disabled={!verified.length} onClick={()=>navigate('API keys')}>Create a key</button></li><li><strong>{sent?'✓ ':''}Send a test email</strong><p>Send from your verified domain to {email}. Uses one email from your allowance.</p>{verified.length>0&&key?<form className="stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setNotice('');const from=new FormData(e.currentTarget).get('from');try{const r=await fetch('/api/onboarding-test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from,request_id:requestId})});const b=await r.json();if(!r.ok)throw Error(typeof b.error==='string'?b.error:b.error?.message||'Send failed');setNotice('Test accepted for delivery. Check your inbox and Email logs.');}catch(e){setNotice(e instanceof Error?e.message:'Send failed');}finally{setBusy(false);}}}><label>From address<input type="email" name="from" required defaultValue={'hello@'+verified[0].name}/></label><button disabled={busy||notice.startsWith('Test accepted')}>{busy?'Sending…':'Send test email'}</button></form>:<p className="caption">Complete the first two steps to send.</p>}{notice&&<p role="status">{notice}</p>}</li></ol></section>;
}
export function Alerts({rows,navigate}:{rows:Row[];navigate:(t:string)=>void}){return <section className="panel"><h2>Failure alerts</h2><p>Checks run when you refresh and during scheduled processing. Resolved problems remain in the history.</p>{rows.length?rows.map(a=><article className="record" key={a.source_key}><div className="record-head"><h3>{a.title}</h3><span className={'badge '+(a.status==='open'?'failed':'verified')}>{a.status}</span></div><p>{a.detail}</p><p className="caption">{a.source_key} · {new Date(a.created_at).toLocaleString()}</p><button className="secondary" onClick={()=>navigate(a.category==='billing'?'Usage & billing':a.category==='webhook'?'Webhooks':a.source_key.startsWith('send/')?'Email logs':'Actions')}>View details</button></article>):<p>No failures detected in this workspace.</p>}</section>;}
