'use client';
import { useEffect,useState,useCallback } from 'react';
type Row=Record<string,any>;
const tabs=['Overview','Agents','Email identities','Policies','Conversations','Approvals','Actions','Audit trail','Settings'];
const descriptions:Record<string,string>={Overview:'Your agents at work. Your decisions in focus.',Agents:'Define what each agent does and when it can act.','Email identities':'Real addresses, assigned to the right agent.',Policies:'Explicit authority. Human approval when no rule matches.',Conversations:'The complete exchange, from first message to reply.',Approvals:'Review the exact reply before it leaves your inbox.',Actions:'Every proposed reply and its execution status.','Audit trail':'A chronological record of decisions and activity.',Settings:'Connection status and workspace access.'};
const time=(v:string)=>v?new Date(v).toLocaleString(): '—';
function Badge({value}:{value:string}){return <span className={'badge '+value}>{value?.replaceAll('_',' ')}</span>;}
function Empty({title,children}:{title:string;children?:React.ReactNode}){return <div className="empty"><strong>{title}</strong>{children}</div>;}
export default function Dashboard({email}:{email:string}){
 const [tab,setTab]=useState('Overview'),[data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState(false),[selected,setSelected]=useState<Row|null>(null),[messages,setMessages]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null),[domains,setDomains]=useState<Row[]>([]);
 const load=useCallback(async()=>{const r=await fetch('/api/state',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);},[]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[load]);
 useEffect(()=>{const i=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(i);},[load]);
 function navigate(t:string){setTab(t);setForm(false);setEdit(null);setSelected(null);setError('');setNotice('');}
 async function act(path:string,payload:Row={},success='Saved.'){
  setBusy(true);setError('');setNotice('');
  try{const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const body=await r.json();if(!r.ok)throw new Error(body.error);await load();setNotice(success);setForm(false);setEdit(null);return true;}
  catch(e){setError(e instanceof Error?e.message:'Request failed');await load().catch(()=>{});return false;}finally{setBusy(false);}
 }
 async function openConversation(row:Row){setSelected(row);setMessages([]);setError('');try{const r=await fetch('/api/conversations/'+row.id);const b=await r.json();if(!r.ok)throw new Error(b.error);setMessages(b.messages);}catch(e){setError(String(e));}}
 function fields(event:React.FormEvent<HTMLFormElement>){event.preventDefault();return Object.fromEntries(new FormData(event.currentTarget));}
 const pending=data?.approvals.filter((a:Row)=>a.status==='pending')||[];
 const agentSelect=<label>Agent<select name="agent_id" required>{data?.agents.map((a:Row)=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>;
 const approvalCard=(a:Row)=><article className="record" key={a.id}><div className="record-head"><h3>{a.payload.subject}</h3><Badge value={a.status}/></div><div className="caption">{a.agent_name} · To {a.payload.to}</div><p className="caption" style={{marginTop:12}}>{a.rationale}</p><div className="message-body">{a.payload.text}</div><div className="caption">From {a.payload.from}</div>{a.status==='pending'?<div className="actions"><button disabled={busy} onClick={()=>act('approvals/'+a.id+'/approve',{},'Approved. The reply was accepted by Resend.')}>Approve & send ↗</button><button className="secondary" disabled={busy} onClick={()=>act('approvals/'+a.id+'/reject',{},'Reply rejected. No email was sent.')}>Reject</button></div>:<p className="caption">{a.decided_by} · {time(a.decided_at)}</p>}</article>;
 const eventList=(rows:Row[])=>rows.map((e:Row)=><div className="event" key={e.id}><span className="event-mark"/><div><strong>{e.event_type.replaceAll('.',' / ').replaceAll('_',' ')}</strong><small>{time(e.created_at)} · {e.actor_id||e.actor_type}</small>{tab==='Audit trail'&&<details><summary>Event details</summary><pre>{JSON.stringify(e.data,null,2)}</pre></details>}</div></div>);
 return <div className="shell"><aside className="sidebar"><a className="brand" href="/">↗ Governed / Email</a><div><div className="workspace-label">WORKSPACE</div><nav className="nav-items" aria-label="Workspace">{tabs.map(t=><button key={t} className={tab===t?'active':''} onClick={()=>navigate(t)}>{t}{t==='Approvals'&&pending.length>0?' · '+pending.length:''}</button>)}</nav></div><div className="sidebar-bottom"><p><span className="dot"/>Governed by default</p><p>{email}</p><a href="/signout-with-chatgpt?return_to=/" target="_top">Sign out ↗</a></div></aside><main className="content"><div className="workspace-top"><span>Workspace / {tab}</span><span>AgentMail Platform · MVP</span></div><header className="page-heading"><div><h1>{tab}</h1><p>{descriptions[tab]}</p></div><button className="secondary" disabled={busy} onClick={()=>{setError('');load().catch(e=>setError(e.message));}}>Refresh ↻</button></header>{error&&<div className="error" role="alert">{error}</div>}{notice&&<div className="notice" role="status">{notice}</div>}{!data?<section className="panel"><Empty title={error?'Workspace unavailable':'Loading your workspace…'}>{error?'Check Settings or refresh to try again.':'Retrieving agents, conversations, and decisions.'}</Empty></section>:<>
 {tab==='Overview'&&<><div className="stats">{[['Active agents',data.stats.active_agents],['Conversations',data.stats.conversations],['Awaiting approval',data.stats.pending],['Replies sent',data.stats.sent]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="split"><section className="panel"><div className="panel-header"><h2>Your review queue</h2><button className="secondary" onClick={()=>navigate('Approvals')}>View all →</button></div><div className="stack">{pending.length?pending.slice(0,3).map(approvalCard):<Empty title="Nothing waiting on you">New replies that need permission will appear here.</Empty>}</div></section><section className="panel"><h2>Recent activity</h2>{data.audit.length?eventList(data.audit.slice(0,7)):<Empty title="A clean slate">Create an agent and assign an email identity to get started.</Empty>}</section></div><section className="panel"><h2>Your first conversation</h2><p>Create an agent → assign an address → send it an email → review the reply.</p><div className="actions"><button onClick={()=>{navigate('Agents');setForm(true);}}>Create an agent +</button><button className="secondary" onClick={()=>navigate('Email identities')}>Manage email identities</button></div></section></>}
 {tab==='Agents'&&<><div className="panel-header"><span className="caption">{data.agents.length} agents</span><button onClick={()=>{setForm(!form);setEdit(null);}}>New agent +</button></div>{(form||edit)&&<form className="panel form-grid" onSubmit={e=>{const b=fields(e);act(edit?'agents/'+edit.id:'agents',b,'Agent saved. Human approval is the default.');}} key={edit?.id||'new'}><label className="wide">Agent name<input name="name" defaultValue={edit?.name||''} placeholder="Customer support" minLength={2} maxLength={100} required/></label><label className="wide">Instructions<textarea name="instructions" defaultValue={edit?.instructions||''} placeholder="Describe your product, tone, and what this agent should help with. Do not include secrets." minLength={10} maxLength={12000} required/></label><div className="wide caption">No matching policy? The reply waits for a human. Instructions do not grant permission to send.</div><div className="actions wide"><button disabled={busy}>Save agent</button><button type="button" className="secondary" onClick={()=>{setForm(false);setEdit(null);}}>Cancel</button></div></form>}<div className="stack">{data.agents.length?data.agents.map((a:Row)=><article className="record" key={a.id}><div className="record-head"><h3>{a.name}</h3><Badge value={a.status}/></div><p className="caption">{data.identities.filter((i:Row)=>i.agent_id===a.id).map((i:Row)=>i.address).join(', ')||'No email identity assigned'}</p><p style={{whiteSpace:'pre-wrap'}}>{a.instructions}</p><div className="actions"><button className="secondary" onClick={()=>{setEdit(a);setForm(false);}}>Edit instructions</button><button className="secondary" disabled={busy} onClick={()=>act('agents/'+a.id,{status:a.status==='active'?'paused':'active'},a.status==='active'?'Agent paused. New messages are held for retry.':'Agent resumed.')}>{a.status==='active'?'Pause agent':'Resume agent'}</button></div></article>):<Empty title="Create your first agent">Give it a name and clear instructions.</Empty>}</div></>}
 {tab==='Email identities'&&<><div className="panel-header"><span className="caption">Use a new address on a verified domain with receiving enabled.</span><button disabled={!data.agents.length} onClick={async()=>{setForm(!form);try{const r=await fetch('/api/domains');const b=await r.json();setDomains(b.data||[]);}catch{}}}>Assign address +</button></div>{form&&<form className="panel form-grid" onSubmit={e=>act('identities',fields(e),'Email identity assigned. You can send it a message now.')} >{agentSelect}<label>Email address<input type="email" name="address" required placeholder="agent-demo@yourdomain.com"/></label><p className="caption wide">Choose an address dedicated to this agent. Receiving is shared at the domain level; existing services keep their webhook. Verified domains: {domains.filter(d=>d.status==='verified').map(d=>d.name).join(', ')||'Loading…'}</p><button disabled={busy}>Assign identity</button></form>}<div className="stack">{data.identities.length?data.identities.map((i:Row)=><article className="record" key={i.id}><div className="record-head"><h3>{i.address}</h3><Badge value={i.status}/></div><p className="caption">{i.agent_name} · Resend · {i.provider_domain}</p><div className="actions"><a className="button secondary" href={'mailto:'+i.address}>Send a test email ↗</a><button className="secondary" disabled={busy} onClick={()=>act('identities/'+i.id,{status:i.status==='active'?'disabled':'active'})}>{i.status==='active'?'Disable':'Enable'}</button></div></article>):<Empty title="No email identities yet">Create an agent, then assign a dedicated address.</Empty>}</div></>}
 {tab==='Policies'&&<><div className="notice">Rules run in priority order, lowest number first. The first matching rule wins. No match always requires human approval.</div><div className="panel-header"><span className="caption">Policy conditions use exact recipient matching.</span><button disabled={!data.agents.length} onClick={()=>setForm(!form)}>New policy +</button></div>{form&&<form className="panel form-grid" onSubmit={e=>{const b=fields(e);act('policies',{...b,priority:Number(b.priority)},'Policy saved.');}}>{agentSelect}<label>Policy name<input name="name" required minLength={2} placeholder="Review all replies"/></label><label>Decision<select name="effect" defaultValue="require_approval"><option value="require_approval">Require approval</option><option value="block">Block</option><option value="allow">Allow automatic sending</option></select></label><label>Priority<input name="priority" type="number" defaultValue={100} min={0} max={10000} required/></label><label className="wide">Only this recipient (optional)<input type="email" name="recipient" placeholder="Leave blank to match all email replies"/></label><p className="caption wide">An Allow rule sends matching replies automatically. Use a specific recipient for a controlled test. Instructions alone never bypass policies.</p><button disabled={busy}>Save policy</button></form>}<div className="stack">{data.policies.length?data.policies.map((p:Row)=><article className="record" key={p.id}><div className="record-head"><h3>{p.name}</h3><Badge value={p.effect}/></div><p className="caption">{p.agent_name} · Priority {p.priority} · {p.condition_json.to?'To '+p.condition_json.to:'All recipients'} · {p.enabled?'Enabled':'Disabled'}</p><button className="secondary" disabled={busy} onClick={()=>act('policies/'+p.id,{enabled:!p.enabled})}>{p.enabled?'Disable rule':'Enable rule'}</button></article>):<Empty title="Human approval is your default">Add a rule only when you want to change an agent’s authority.</Empty>}</div></>}
 {tab==='Conversations'&&<>{selected?<section className="panel"><button className="secondary" onClick={()=>setSelected(null)}>← All conversations</button><h2 style={{marginTop:24}}>{selected.subject}</h2><p>{selected.agent_name} · {selected.participant_email}</p>{messages.map(m=><article className={'message '+m.direction} key={m.id}><div className="record-head"><strong>{m.direction==='inbound'?'Received':'Sent'}</strong><small>{time(m.created_at)}</small></div><small>{m.from_address} → {m.to_address}</small><div className="message-body">{m.text_body||'This message has no plain-text body.'}</div></article>)}</section>:<section className="panel"><div className="scroll-table"><table><thead><tr><th>Conversation</th><th>Agent</th><th>Messages</th><th>Last activity</th></tr></thead><tbody>{data.conversations.map((c:Row)=><tr key={c.id}><td><button className="secondary" onClick={()=>openConversation(c)}>{c.subject||'(No subject)'}</button><div className="caption">{c.participant_email}</div></td><td>{c.agent_name}</td><td>{c.message_count}</td><td>{time(c.last_message_at)}</td></tr>)}</tbody></table></div>{!data.conversations.length&&<Empty title="No conversations yet">Send a message to one of your email identities.</Empty>}</section>}</>}
 {tab==='Approvals'&&<><div className="stack">{pending.length?pending.map(approvalCard):<section className="panel"><Empty title="You’re all caught up">Replies that require your permission will appear here.</Empty></section>}</div><section className="panel" style={{marginTop:20}}><h2>Previously reviewed</h2><div className="stack">{data.approvals.filter((a:Row)=>a.status!=='pending').map(approvalCard)}</div></section></>}
 {tab==='Actions'&&<><div className="stack">{data.actions.map((a:Row)=><article className="record" key={a.id}><div className="record-head"><h3>{a.payload.subject}</h3><Badge value={a.status}/></div><p className="caption">{a.agent_name} · {a.payload.to} · {time(a.created_at)}</p><p>{a.reason||'Policy evaluation pending'}</p><details><summary>Reply and rationale</summary><div className="message-body">{a.payload.text}</div><p className="caption">{a.rationale}</p></details>{a.provider_id&&<p className="caption">Resend accepted · {a.provider_id}</p>}{a.last_error&&<p className="error">{a.last_error}</p>}{(a.status==='failed'||(a.approval_status==='approved'&&!['executed','blocked','rejected'].includes(a.status)))&&<button disabled={busy} onClick={()=>act('actions/'+a.id+'/retry',{},'Reply accepted by Resend.')}>Retry sending</button>}</article>)}{!data.actions.length&&<Empty title="No actions proposed yet">Actions appear after an agent processes an inbound email.</Empty>}</div>{data.jobs.length>0&&<section className="panel" style={{marginTop:20}}><h2>Messages needing attention</h2>{data.jobs.map((j:Row)=><div className="record" key={j.provider_message_id}><Badge value={j.status}/><p>{j.last_error}</p><p className="caption">{time(j.created_at)} · {j.attempts} attempts</p><button disabled={busy} onClick={()=>act('jobs/retry',{provider_message_id:j.provider_message_id},'Message processed.')}>Retry processing</button></div>)}</section>}</>}
 {tab==='Audit trail'&&<section className="panel"><div className="panel-header"><h2>Latest 200 events</h2><span className="caption">Read-only activity log</span></div>{data.audit.length?eventList(data.audit):<Empty title="No events yet">Workspace activity will appear here.</Empty>}</section>}
 {tab==='Settings'&&<><section className="panel"><h2>Connected services</h2>{[['Database · AgentMail-Platform',data.config.database],['Email delivery · Resend',data.config.resend],['AI reply drafting',data.config.ai],['Inbound webhook signature',data.config.webhook]].map(([label,ok])=><div className="health-line" key={label as string}><span>{label}</span><Badge value={ok?'configured':'missing'}/></div>)}<p className="caption" style={{marginTop:15}}>Database status is checked on refresh. Other indicators show whether credentials are configured; the email test verifies they work.</p><label>Inbound webhook URL<input value={data.config.webhook_url} readOnly/></label><p className="caption" style={{marginTop:15}}>AI model: {data.config.model}. Credentials are managed as hosting secrets and are never exposed in this dashboard.</p></section><section className="panel"><h2>Access & configuration</h2><p>Signed in as <strong>{email}</strong>. This is a single-workspace MVP with administrator-only access. The landing page is public; messages and controls require sign-in.</p><p>Manage agent instructions in Agents, inbox assignments in Email identities, and authority in Policies.</p><div className="actions"><a className="button secondary" href="https://resend.com/domains" target="_blank" rel="noreferrer">Resend domains ↗</a><a className="button secondary" href="https://resend.com/webhooks" target="_blank" rel="noreferrer">Webhook delivery logs ↗</a></div></section></>}
 </>}</main></div>;
}

